# Books list
BARSTOOL = 0
BETONLINE = 1
BETFAIR = 2
BETMGM = 3
BETRIVERS = 4
BETUS = 5
BOVADA = 6
CAESARS = 7
CIRCA = 8
DRAFTKINGS = 9 
FANDUEL = 10
FOXBET = 11 
LOWVIG = 12 
MYBOOKIE = 13
POINTSBET = 14
SUGARHOUSE = 15
SUPERBOOK = 16 
TWINSPIRES = 17
UNIBET = 18
WYNNBET = 19
BALLY = 20
BETPARX = 21
TIPICO = 22

Books = [
    'barstool',
    'betonlineag',
    'betfair',
    'betmgm',
    'betrivers',
    'betus',
    'bovada',
    'williamhill_us', # Caesar's
    'circasports',
    'draftkings',
    'fanduel',
    'foxbet',
    'lowvig',
    'mybookieag',
    'pointsbetus',
    'sugarhouse',
    'superbook',
    'twinspires',
    'unibet_us',
    'wynnbet',
    'ballybet',
    'betparx',
    'tipico_us'
]

Books_Print = [
    "Barstool Sportsbook",
    "BetOnline.ag",
    "Betfair Exchange",
    "BetMGM",
    "BetRivers",
    "BetUS",
    "Bovada",
    "Caesars Sportsbook",
    "Circa Sports",
    "DraftKings",
    "FanDuel",
    "FOX Bet",
    "LowVig.ag",
    "MyBookie.ag",
    "PointsBet",
    "SugarHouse",
    "SuperBook",
    "TwinSpires",
    "Unibet",
    "WynnBET",
    "Bally Bet",
    "betPARX",
    "Tipico"
]

ALL_BOOKS = [BARSTOOL, BETONLINE, BETFAIR, BETMGM, BETRIVERS, BETUS, BOVADA, CAESARS, CIRCA, DRAFTKINGS, FANDUEL, FOXBET, LOWVIG, MYBOOKIE, POINTSBET, SUGARHOUSE, SUPERBOOK, TWINSPIRES, UNIBET, WYNNBET, BALLY, BETPARX, TIPICO]
OFFSHORE_BOOKS = [BETONLINE, BETFAIR, BETUS, BOVADA, LOWVIG, MYBOOKIE]

AL = []
AK = []
AZ = [BARSTOOL, BETMGM, BETRIVERS, CAESARS, DRAFTKINGS, FANDUEL, SUPERBOOK, TWINSPIRES, UNIBET, WYNNBET, BALLY]
AR = []
CA = []
CO = [BARSTOOL, BETMGM, BETRIVERS, CAESARS, CIRCA, DRAFTKINGS, FANDUEL, FOXBET, POINTSBET, SUPERBOOK, WYNNBET, BALLY]
CT = [DRAFTKINGS, FANDUEL, SUGARHOUSE]
DE = []
FL = []
GA = []
HI = []
ID = []
IL = [BARSTOOL, BETMGM, BETRIVERS, CAESARS, DRAFTKINGS, FANDUEL, POINTSBET]
IN = [BARSTOOL, BETMGM, BETRIVERS, CAESARS, DRAFTKINGS, FANDUEL, POINTSBET, TWINSPIRES, UNIBET, WYNNBET, BALLY]
IA = [BARSTOOL, BETMGM, BETRIVERS, CAESARS, CIRCA, DRAFTKINGS, FANDUEL, POINTSBET, SUPERBOOK, BALLY, TIPICO]
KS = [BARSTOOL, BETMGM, CAESARS, DRAFTKINGS, FANDUEL, POINTSBET]
KY = []
LA = [BARSTOOL, BETMGM, BETRIVERS, CAESARS, DRAFTKINGS, FANDUEL, WYNNBET]
ME = []
MD = [BARSTOOL, BETMGM, BETRIVERS, CAESARS, DRAFTKINGS, FANDUEL, POINTSBET, BETPARX]
MA = [BARSTOOL, BETMGM, CAESARS, DRAFTKINGS, FANDUEL, WYNNBET]
MI = [BARSTOOL, BETMGM, BETRIVERS, CAESARS, DRAFTKINGS, FANDUEL, FOXBET, POINTSBET, TWINSPIRES, WYNNBET, BETPARX]
MN = []
MS = [TWINSPIRES]
MO = []
MT = []
NE = []
NV = [BETMGM, CAESARS, CIRCA, SUPERBOOK, WYNNBET]
NH = [DRAFTKINGS]
NJ = [BARSTOOL, BETMGM, BETRIVERS, CAESARS, DRAFTKINGS, FANDUEL, FOXBET, POINTSBET, SUGARHOUSE, SUPERBOOK, TWINSPIRES, UNIBET, WYNNBET, BETPARX, TIPICO]
NM = []
NY = [BETMGM, BETRIVERS, CAESARS, DRAFTKINGS, FANDUEL, POINTSBET, WYNNBET, BALLY]
NC = []
ND = []
OH = [BARSTOOL, BETMGM, BETRIVERS, CAESARS, DRAFTKINGS, FANDUEL, POINTSBET, SUPERBOOK, BETPARX, TIPICO]
OK = []
OR = [DRAFTKINGS]
PA = [BARSTOOL, BETMGM, BETRIVERS, CAESARS, DRAFTKINGS, FANDUEL, FOXBET, POINTSBET, TWINSPIRES, UNIBET, BETPARX]
RI = []
SC = []
SD = []
TN = [BARSTOOL, BETMGM, CAESARS, DRAFTKINGS, FANDUEL, SUPERBOOK, TWINSPIRES, WYNNBET]
TX = []
UT = []
VT = []
VA = [BARSTOOL, BETMGM, BETRIVERS, CAESARS, DRAFTKINGS, FANDUEL, POINTSBET, UNIBET, WYNNBET, BALLY]
WA = []
WV = [BARSTOOL, BETMGM, CAESARS, DRAFTKINGS, FANDUEL, POINTSBET]
WI = []
WY = [BETMGM, FANDUEL]